package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"

	"github.com/TBXark/sphere/database/bind"
	"github.com/TBXark/sphere/layout/api/entpb"
	"github.com/TBXark/sphere/layout/internal/pkg/database/ent"
	"github.com/TBXark/sphere/layout/internal/pkg/database/ent/admin"
)

func Gen(mod string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`// Code generated by gen-bind. DO NOT EDIT.
package render

import (
	"github.com/TBXark/sphere/database/bind"
	"%s/api/entpb"
	"%s/internal/pkg/database/ent"
)

`, mod, mod))
	for _, act := range []any{ent.AdminCreate{}, ent.AdminUpdateOne{}} {
		sb.WriteString(
			bind.Gen(
				bind.NewGenConf(ent.Admin{}, entpb.Admin{}, act).
					WithTargetPkgName("entpb").
					WithIgnoreFields(admin.FieldCreatedAt, admin.FieldUpdatedAt),
			),
		)
	}
	return sb.String()
}

func main() {
	file := flag.String("file", "./internal/pkg/render/bind.go", "file path")
	mod := flag.String("mod", "", "go module path")
	flag.Parse()
	if *file == "" {
		log.Fatal("file is required")
	}
	if *mod == "" {
		log.Fatal("mod is required")
	}
	fileCont := Gen(*mod)
	source, err := format.Source([]byte(fileCont))
	if err != nil {
		log.Fatalf("format source failed: %v", err)
	}
	err = os.WriteFile(*file, source, 0o644)
	if err != nil {
		log.Fatalf("write file failed: %v", err)
	}
}
