// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             (unknown)
// source: api/v1/user.proto

package apiv1

import (
	context "context"
	gin "github.com/gin-gonic/gin"
	ginx "github.com/tbxark/sphere/pkg/web/ginx"
)

var _ = new(context.Context)
var _ = new(gin.Context)
var _ = new(ginx.DataResponse[string])

type UserServiceHTTPServer interface {
	BindPhoneWxMini(context.Context, *BindPhoneWxMiniRequest) (*BindPhoneWxMiniResponse, error)
	Me(context.Context, *MeRequest) (*MeResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

// @Summary Me
// @Description Me
// @Tags api.v1
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Success 200 {object} ginx.DataResponse[MeResponse]
// @Router /api/user/me [get]
func _UserService_Me0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx *gin.Context) {
	return ginx.WithJson(func(ctx *gin.Context) (*MeResponse, error) {
		var in MeRequest
		out, err := srv.Me(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary Update
// @Description Update
// @Tags api.v1
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param request body UpdateRequest true "Request body"
// @Success 200 {object} ginx.DataResponse[UpdateResponse]
// @Router /api/user/update [post]
func _UserService_Update0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx *gin.Context) {
	return ginx.WithJson(func(ctx *gin.Context) (*UpdateResponse, error) {
		var in UpdateRequest
		if err := ctx.ShouldBindJSON(&in); err != nil {
			return nil, err
		}
		out, err := srv.Update(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary BindPhoneWxMini
// @Description BindPhoneWxMini
// @Tags api.v1
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param request body BindPhoneWxMiniRequest true "Request body"
// @Success 200 {object} ginx.DataResponse[BindPhoneWxMiniResponse]
// @Router /api/user/bind/phone/wxmini [post]
func _UserService_BindPhoneWxMini0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx *gin.Context) {
	return ginx.WithJson(func(ctx *gin.Context) (*BindPhoneWxMiniResponse, error) {
		var in BindPhoneWxMiniRequest
		if err := ctx.ShouldBindJSON(&in); err != nil {
			return nil, err
		}
		out, err := srv.BindPhoneWxMini(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterUserServiceHTTPServer(route gin.IRouter, srv UserServiceHTTPServer) {
	r := route.Group("/")
	r.GET("/api/user/me", _UserService_Me0_HTTP_Handler(srv))
	r.POST("/api/user/update", _UserService_Update0_HTTP_Handler(srv))
	r.POST("/api/user/bind/phone/wxmini", _UserService_BindPhoneWxMini0_HTTP_Handler(srv))
}
