// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sphere/errors/errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_sphere_errors_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_sphere_errors_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_sphere_errors_errors_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var file_sphere_errors_errors_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*Error)(nil),
		Field:         114516,
		Name:          "sphere.errors.options",
		Tag:           "bytes,114516,opt,name=options",
		Filename:      "sphere/errors/errors.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional sphere.errors.Error options = 114516;
	E_Options = &file_sphere_errors_errors_proto_extTypes[0]
)

var File_sphere_errors_errors_proto protoreflect.FileDescriptor

const file_sphere_errors_errors_proto_rawDesc = "" +
	"\n" +
	"\x1asphere/errors/errors.proto\x12\rsphere.errors\x1a google/protobuf/descriptor.proto\"c\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage:S\n" +
	"\aoptions\x12!.google.protobuf.EnumValueOptions\x18\xd4\xfe\x06 \x01(\v2\x14.sphere.errors.ErrorR\aoptionsB\xab\x01\n" +
	"\x11com.sphere.errorsB\vErrorsProtoP\x01Z4github.com/TBXark/sphere/proto/options/sphere/errors\xa2\x02\x03SEX\xaa\x02\rSphere.Errors\xca\x02\rSphere\\Errors\xe2\x02\x19Sphere\\Errors\\GPBMetadata\xea\x02\x0eSphere::Errorsb\x06proto3"

var (
	file_sphere_errors_errors_proto_rawDescOnce sync.Once
	file_sphere_errors_errors_proto_rawDescData []byte
)

func file_sphere_errors_errors_proto_rawDescGZIP() []byte {
	file_sphere_errors_errors_proto_rawDescOnce.Do(func() {
		file_sphere_errors_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sphere_errors_errors_proto_rawDesc), len(file_sphere_errors_errors_proto_rawDesc)))
	})
	return file_sphere_errors_errors_proto_rawDescData
}

var file_sphere_errors_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sphere_errors_errors_proto_goTypes = []any{
	(*Error)(nil),                         // 0: sphere.errors.Error
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_sphere_errors_errors_proto_depIdxs = []int32{
	1, // 0: sphere.errors.options:extendee -> google.protobuf.EnumValueOptions
	0, // 1: sphere.errors.options:type_name -> sphere.errors.Error
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sphere_errors_errors_proto_init() }
func file_sphere_errors_errors_proto_init() {
	if File_sphere_errors_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sphere_errors_errors_proto_rawDesc), len(file_sphere_errors_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_sphere_errors_errors_proto_goTypes,
		DependencyIndexes: file_sphere_errors_errors_proto_depIdxs,
		MessageInfos:      file_sphere_errors_errors_proto_msgTypes,
		ExtensionInfos:    file_sphere_errors_errors_proto_extTypes,
	}.Build()
	File_sphere_errors_errors_proto = out.File
	file_sphere_errors_errors_proto_goTypes = nil
	file_sphere_errors_errors_proto_depIdxs = nil
}
