// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sphere/binding/binding.proto

package binding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindingLocation int32

const (
	BindingLocation_BINDING_LOCATION_UNSPECIFIED BindingLocation = 0 // Default value, should not be used.
	BindingLocation_BINDING_LOCATION_QUERY       BindingLocation = 1 // Indicates that the binding is for query parameters.
	BindingLocation_BINDING_LOCATION_URI         BindingLocation = 2 // Indicates that the binding is for URI parameters.
	BindingLocation_BINDING_LOCATION_BODY        BindingLocation = 3 // Indicates that the binding is for the body of the request.
)

// Enum value maps for BindingLocation.
var (
	BindingLocation_name = map[int32]string{
		0: "BINDING_LOCATION_UNSPECIFIED",
		1: "BINDING_LOCATION_QUERY",
		2: "BINDING_LOCATION_URI",
		3: "BINDING_LOCATION_BODY",
	}
	BindingLocation_value = map[string]int32{
		"BINDING_LOCATION_UNSPECIFIED": 0,
		"BINDING_LOCATION_QUERY":       1,
		"BINDING_LOCATION_URI":         2,
		"BINDING_LOCATION_BODY":        3,
	}
)

func (x BindingLocation) Enum() *BindingLocation {
	p := new(BindingLocation)
	*p = x
	return p
}

func (x BindingLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindingLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_sphere_binding_binding_proto_enumTypes[0].Descriptor()
}

func (BindingLocation) Type() protoreflect.EnumType {
	return &file_sphere_binding_binding_proto_enumTypes[0]
}

func (x BindingLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindingLocation.Descriptor instead.
func (BindingLocation) EnumDescriptor() ([]byte, []int) {
	return file_sphere_binding_binding_proto_rawDescGZIP(), []int{0}
}

var file_sphere_binding_binding_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*BindingLocation)(nil),
		Field:         114520,
		Name:          "sphere.binding.default_location",
		Tag:           "varint,114520,opt,name=default_location,enum=sphere.binding.BindingLocation",
		Filename:      "sphere/binding/binding.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*BindingLocation)(nil),
		Field:         114523,
		Name:          "sphere.binding.location",
		Tag:           "varint,114523,opt,name=location,enum=sphere.binding.BindingLocation",
		Filename:      "sphere/binding/binding.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional sphere.binding.BindingLocation default_location = 114520;
	E_DefaultLocation = &file_sphere_binding_binding_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional sphere.binding.BindingLocation location = 114523;
	E_Location = &file_sphere_binding_binding_proto_extTypes[1]
)

var File_sphere_binding_binding_proto protoreflect.FileDescriptor

const file_sphere_binding_binding_proto_rawDesc = "" +
	"\n" +
	"\x1csphere/binding/binding.proto\x12\x0esphere.binding\x1a google/protobuf/descriptor.proto*\x84\x01\n" +
	"\x0fBindingLocation\x12 \n" +
	"\x1cBINDING_LOCATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BINDING_LOCATION_QUERY\x10\x01\x12\x18\n" +
	"\x14BINDING_LOCATION_URI\x10\x02\x12\x19\n" +
	"\x15BINDING_LOCATION_BODY\x10\x03:p\n" +
	"\x10default_location\x12\x1f.google.protobuf.MessageOptions\x18\xd8\xfe\x06 \x01(\x0e2\x1f.sphere.binding.BindingLocationR\x0fdefaultLocation\x88\x01\x01:_\n" +
	"\blocation\x12\x1d.google.protobuf.FieldOptions\x18\xdb\xfe\x06 \x01(\x0e2\x1f.sphere.binding.BindingLocationR\blocation\x88\x01\x01B\xb2\x01\n" +
	"\x12com.sphere.bindingB\fBindingProtoP\x01Z5github.com/TBXark/sphere/proto/binding/sphere/binding\xa2\x02\x03SBX\xaa\x02\x0eSphere.Binding\xca\x02\x0eSphere\\Binding\xe2\x02\x1aSphere\\Binding\\GPBMetadata\xea\x02\x0fSphere::Bindingb\x06proto3"

var (
	file_sphere_binding_binding_proto_rawDescOnce sync.Once
	file_sphere_binding_binding_proto_rawDescData []byte
)

func file_sphere_binding_binding_proto_rawDescGZIP() []byte {
	file_sphere_binding_binding_proto_rawDescOnce.Do(func() {
		file_sphere_binding_binding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sphere_binding_binding_proto_rawDesc), len(file_sphere_binding_binding_proto_rawDesc)))
	})
	return file_sphere_binding_binding_proto_rawDescData
}

var file_sphere_binding_binding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sphere_binding_binding_proto_goTypes = []any{
	(BindingLocation)(0),                // 0: sphere.binding.BindingLocation
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
}
var file_sphere_binding_binding_proto_depIdxs = []int32{
	1, // 0: sphere.binding.default_location:extendee -> google.protobuf.MessageOptions
	2, // 1: sphere.binding.location:extendee -> google.protobuf.FieldOptions
	0, // 2: sphere.binding.default_location:type_name -> sphere.binding.BindingLocation
	0, // 3: sphere.binding.location:type_name -> sphere.binding.BindingLocation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sphere_binding_binding_proto_init() }
func file_sphere_binding_binding_proto_init() {
	if File_sphere_binding_binding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sphere_binding_binding_proto_rawDesc), len(file_sphere_binding_binding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_sphere_binding_binding_proto_goTypes,
		DependencyIndexes: file_sphere_binding_binding_proto_depIdxs,
		EnumInfos:         file_sphere_binding_binding_proto_enumTypes,
		ExtensionInfos:    file_sphere_binding_binding_proto_extTypes,
	}.Build()
	File_sphere_binding_binding_proto = out.File
	file_sphere_binding_binding_proto_goTypes = nil
	file_sphere_binding_binding_proto_depIdxs = nil
}
