package bind

import (
	_ "embed"
	"go/format"
	"path"
	"strconv"
	"strings"
)

type GenFileConf struct {
	Entities     []GenFileEntityConf
	ExtraImports [][2]string
}

type GenFileEntityConf struct {
	Actions       []any
	ConfigBuilder func(act any) *GenFuncConf
}

func GenFile(config *GenFileConf) (string, error) {
	var file strings.Builder
	var body strings.Builder

	imports := [][2]string{
		PackageImport(Options{}),
	}
	for _, item := range config.Entities {
		for i, act := range item.Actions {
			conf := item.ConfigBuilder(act)
			imports = append(imports,
				PackageImport(act),
				PackageImport(conf.source),
				PackageImport(conf.target),
			)
			if i == 0 {
				entityName := strings.ToLower(typeName(conf.source))
				imports = append(imports, [2]string{
					path.Join(packagePath(conf.source), entityName),
					entityName,
				})
			}
			funcContent, err := GenBindFunc(conf)
			if err != nil {
				return "", err
			}
			body.WriteString(funcContent)
			body.WriteString("\n")
		}
	}
	imports = append(imports, config.ExtraImports...)

	file.WriteString("// Code generated by Sphere. DO NOT EDIT.\n")
	file.WriteString("package render\n\n")
	file.WriteString("import (\n")
	for _, imp := range compressedImports(imports) {
		file.WriteString("\t")
		if imp[1] != "" {
			file.WriteString(imp[1] + " ")
		}
		file.WriteString(strconv.Quote(imp[0]) + "\n")
	}
	file.WriteString(")\n\n")
	file.WriteString(body.String())

	source, err := format.Source([]byte(file.String()))
	if err != nil {
		return "", err
	}
	return string(source), nil
}
