// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tbxark/go-base-api/pkg/dao/ent/keyvaluestore"
	"github.com/tbxark/go-base-api/pkg/dao/ent/predicate"
)

// KeyValueStoreQuery is the builder for querying KeyValueStore entities.
type KeyValueStoreQuery struct {
	config
	ctx        *QueryContext
	order      []keyvaluestore.OrderOption
	inters     []Interceptor
	predicates []predicate.KeyValueStore
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the KeyValueStoreQuery builder.
func (kvsq *KeyValueStoreQuery) Where(ps ...predicate.KeyValueStore) *KeyValueStoreQuery {
	kvsq.predicates = append(kvsq.predicates, ps...)
	return kvsq
}

// Limit the number of records to be returned by this query.
func (kvsq *KeyValueStoreQuery) Limit(limit int) *KeyValueStoreQuery {
	kvsq.ctx.Limit = &limit
	return kvsq
}

// Offset to start from.
func (kvsq *KeyValueStoreQuery) Offset(offset int) *KeyValueStoreQuery {
	kvsq.ctx.Offset = &offset
	return kvsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (kvsq *KeyValueStoreQuery) Unique(unique bool) *KeyValueStoreQuery {
	kvsq.ctx.Unique = &unique
	return kvsq
}

// Order specifies how the records should be ordered.
func (kvsq *KeyValueStoreQuery) Order(o ...keyvaluestore.OrderOption) *KeyValueStoreQuery {
	kvsq.order = append(kvsq.order, o...)
	return kvsq
}

// First returns the first KeyValueStore entity from the query.
// Returns a *NotFoundError when no KeyValueStore was found.
func (kvsq *KeyValueStoreQuery) First(ctx context.Context) (*KeyValueStore, error) {
	nodes, err := kvsq.Limit(1).All(setContextOp(ctx, kvsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{keyvaluestore.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (kvsq *KeyValueStoreQuery) FirstX(ctx context.Context) *KeyValueStore {
	node, err := kvsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first KeyValueStore ID from the query.
// Returns a *NotFoundError when no KeyValueStore ID was found.
func (kvsq *KeyValueStoreQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = kvsq.Limit(1).IDs(setContextOp(ctx, kvsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{keyvaluestore.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (kvsq *KeyValueStoreQuery) FirstIDX(ctx context.Context) int {
	id, err := kvsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single KeyValueStore entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one KeyValueStore entity is found.
// Returns a *NotFoundError when no KeyValueStore entities are found.
func (kvsq *KeyValueStoreQuery) Only(ctx context.Context) (*KeyValueStore, error) {
	nodes, err := kvsq.Limit(2).All(setContextOp(ctx, kvsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{keyvaluestore.Label}
	default:
		return nil, &NotSingularError{keyvaluestore.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (kvsq *KeyValueStoreQuery) OnlyX(ctx context.Context) *KeyValueStore {
	node, err := kvsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only KeyValueStore ID in the query.
// Returns a *NotSingularError when more than one KeyValueStore ID is found.
// Returns a *NotFoundError when no entities are found.
func (kvsq *KeyValueStoreQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = kvsq.Limit(2).IDs(setContextOp(ctx, kvsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{keyvaluestore.Label}
	default:
		err = &NotSingularError{keyvaluestore.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (kvsq *KeyValueStoreQuery) OnlyIDX(ctx context.Context) int {
	id, err := kvsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of KeyValueStores.
func (kvsq *KeyValueStoreQuery) All(ctx context.Context) ([]*KeyValueStore, error) {
	ctx = setContextOp(ctx, kvsq.ctx, "All")
	if err := kvsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*KeyValueStore, *KeyValueStoreQuery]()
	return withInterceptors[[]*KeyValueStore](ctx, kvsq, qr, kvsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (kvsq *KeyValueStoreQuery) AllX(ctx context.Context) []*KeyValueStore {
	nodes, err := kvsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of KeyValueStore IDs.
func (kvsq *KeyValueStoreQuery) IDs(ctx context.Context) (ids []int, err error) {
	if kvsq.ctx.Unique == nil && kvsq.path != nil {
		kvsq.Unique(true)
	}
	ctx = setContextOp(ctx, kvsq.ctx, "IDs")
	if err = kvsq.Select(keyvaluestore.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (kvsq *KeyValueStoreQuery) IDsX(ctx context.Context) []int {
	ids, err := kvsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (kvsq *KeyValueStoreQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, kvsq.ctx, "Count")
	if err := kvsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, kvsq, querierCount[*KeyValueStoreQuery](), kvsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (kvsq *KeyValueStoreQuery) CountX(ctx context.Context) int {
	count, err := kvsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (kvsq *KeyValueStoreQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, kvsq.ctx, "Exist")
	switch _, err := kvsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (kvsq *KeyValueStoreQuery) ExistX(ctx context.Context) bool {
	exist, err := kvsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the KeyValueStoreQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (kvsq *KeyValueStoreQuery) Clone() *KeyValueStoreQuery {
	if kvsq == nil {
		return nil
	}
	return &KeyValueStoreQuery{
		config:     kvsq.config,
		ctx:        kvsq.ctx.Clone(),
		order:      append([]keyvaluestore.OrderOption{}, kvsq.order...),
		inters:     append([]Interceptor{}, kvsq.inters...),
		predicates: append([]predicate.KeyValueStore{}, kvsq.predicates...),
		// clone intermediate query.
		sql:  kvsq.sql.Clone(),
		path: kvsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.KeyValueStore.Query().
//		GroupBy(keyvaluestore.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (kvsq *KeyValueStoreQuery) GroupBy(field string, fields ...string) *KeyValueStoreGroupBy {
	kvsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &KeyValueStoreGroupBy{build: kvsq}
	grbuild.flds = &kvsq.ctx.Fields
	grbuild.label = keyvaluestore.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//	}
//
//	client.KeyValueStore.Query().
//		Select(keyvaluestore.FieldCreatedAt).
//		Scan(ctx, &v)
func (kvsq *KeyValueStoreQuery) Select(fields ...string) *KeyValueStoreSelect {
	kvsq.ctx.Fields = append(kvsq.ctx.Fields, fields...)
	sbuild := &KeyValueStoreSelect{KeyValueStoreQuery: kvsq}
	sbuild.label = keyvaluestore.Label
	sbuild.flds, sbuild.scan = &kvsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a KeyValueStoreSelect configured with the given aggregations.
func (kvsq *KeyValueStoreQuery) Aggregate(fns ...AggregateFunc) *KeyValueStoreSelect {
	return kvsq.Select().Aggregate(fns...)
}

func (kvsq *KeyValueStoreQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range kvsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, kvsq); err != nil {
				return err
			}
		}
	}
	for _, f := range kvsq.ctx.Fields {
		if !keyvaluestore.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if kvsq.path != nil {
		prev, err := kvsq.path(ctx)
		if err != nil {
			return err
		}
		kvsq.sql = prev
	}
	return nil
}

func (kvsq *KeyValueStoreQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*KeyValueStore, error) {
	var (
		nodes = []*KeyValueStore{}
		_spec = kvsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*KeyValueStore).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &KeyValueStore{config: kvsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(kvsq.modifiers) > 0 {
		_spec.Modifiers = kvsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, kvsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (kvsq *KeyValueStoreQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := kvsq.querySpec()
	if len(kvsq.modifiers) > 0 {
		_spec.Modifiers = kvsq.modifiers
	}
	_spec.Node.Columns = kvsq.ctx.Fields
	if len(kvsq.ctx.Fields) > 0 {
		_spec.Unique = kvsq.ctx.Unique != nil && *kvsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, kvsq.driver, _spec)
}

func (kvsq *KeyValueStoreQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(keyvaluestore.Table, keyvaluestore.Columns, sqlgraph.NewFieldSpec(keyvaluestore.FieldID, field.TypeInt))
	_spec.From = kvsq.sql
	if unique := kvsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if kvsq.path != nil {
		_spec.Unique = true
	}
	if fields := kvsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, keyvaluestore.FieldID)
		for i := range fields {
			if fields[i] != keyvaluestore.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := kvsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := kvsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := kvsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := kvsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (kvsq *KeyValueStoreQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(kvsq.driver.Dialect())
	t1 := builder.Table(keyvaluestore.Table)
	columns := kvsq.ctx.Fields
	if len(columns) == 0 {
		columns = keyvaluestore.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if kvsq.sql != nil {
		selector = kvsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if kvsq.ctx.Unique != nil && *kvsq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range kvsq.modifiers {
		m(selector)
	}
	for _, p := range kvsq.predicates {
		p(selector)
	}
	for _, p := range kvsq.order {
		p(selector)
	}
	if offset := kvsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := kvsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (kvsq *KeyValueStoreQuery) Modify(modifiers ...func(s *sql.Selector)) *KeyValueStoreSelect {
	kvsq.modifiers = append(kvsq.modifiers, modifiers...)
	return kvsq.Select()
}

// KeyValueStoreGroupBy is the group-by builder for KeyValueStore entities.
type KeyValueStoreGroupBy struct {
	selector
	build *KeyValueStoreQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (kvsgb *KeyValueStoreGroupBy) Aggregate(fns ...AggregateFunc) *KeyValueStoreGroupBy {
	kvsgb.fns = append(kvsgb.fns, fns...)
	return kvsgb
}

// Scan applies the selector query and scans the result into the given value.
func (kvsgb *KeyValueStoreGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, kvsgb.build.ctx, "GroupBy")
	if err := kvsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*KeyValueStoreQuery, *KeyValueStoreGroupBy](ctx, kvsgb.build, kvsgb, kvsgb.build.inters, v)
}

func (kvsgb *KeyValueStoreGroupBy) sqlScan(ctx context.Context, root *KeyValueStoreQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(kvsgb.fns))
	for _, fn := range kvsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*kvsgb.flds)+len(kvsgb.fns))
		for _, f := range *kvsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*kvsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := kvsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// KeyValueStoreSelect is the builder for selecting fields of KeyValueStore entities.
type KeyValueStoreSelect struct {
	*KeyValueStoreQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (kvss *KeyValueStoreSelect) Aggregate(fns ...AggregateFunc) *KeyValueStoreSelect {
	kvss.fns = append(kvss.fns, fns...)
	return kvss
}

// Scan applies the selector query and scans the result into the given value.
func (kvss *KeyValueStoreSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, kvss.ctx, "Select")
	if err := kvss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*KeyValueStoreQuery, *KeyValueStoreSelect](ctx, kvss.KeyValueStoreQuery, kvss, kvss.inters, v)
}

func (kvss *KeyValueStoreSelect) sqlScan(ctx context.Context, root *KeyValueStoreQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(kvss.fns))
	for _, fn := range kvss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*kvss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := kvss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (kvss *KeyValueStoreSelect) Modify(modifiers ...func(s *sql.Selector)) *KeyValueStoreSelect {
	kvss.modifiers = append(kvss.modifiers, modifiers...)
	return kvss
}
