// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/tbxark/go-base-api/pkg/dao/ent/userplatform"
)

// UserPlatform is the model entity for the UserPlatform schema.
type UserPlatform struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 创建时间
	CreatedAt int64 `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// 用户ID
	UserID int `json:"user_id,omitempty"`
	// 平台
	Platform string `json:"platform,omitempty"`
	// 平台ID
	PlatformID string `json:"platform_id,omitempty"`
	// 第二ID
	SecondID     string `json:"second_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPlatform) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userplatform.FieldID, userplatform.FieldCreatedAt, userplatform.FieldUpdatedAt, userplatform.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userplatform.FieldPlatform, userplatform.FieldPlatformID, userplatform.FieldSecondID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPlatform fields.
func (up *UserPlatform) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userplatform.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			up.ID = int(value.Int64)
		case userplatform.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				up.CreatedAt = value.Int64
			}
		case userplatform.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				up.UpdatedAt = value.Int64
			}
		case userplatform.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				up.UserID = int(value.Int64)
			}
		case userplatform.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				up.Platform = value.String
			}
		case userplatform.FieldPlatformID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_id", values[i])
			} else if value.Valid {
				up.PlatformID = value.String
			}
		case userplatform.FieldSecondID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field second_id", values[i])
			} else if value.Valid {
				up.SecondID = value.String
			}
		default:
			up.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserPlatform.
// This includes values selected through modifiers, order, etc.
func (up *UserPlatform) Value(name string) (ent.Value, error) {
	return up.selectValues.Get(name)
}

// Update returns a builder for updating this UserPlatform.
// Note that you need to call UserPlatform.Unwrap() before calling this method if this UserPlatform
// was returned from a transaction, and the transaction was committed or rolled back.
func (up *UserPlatform) Update() *UserPlatformUpdateOne {
	return NewUserPlatformClient(up.config).UpdateOne(up)
}

// Unwrap unwraps the UserPlatform entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (up *UserPlatform) Unwrap() *UserPlatform {
	_tx, ok := up.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPlatform is not a transactional entity")
	}
	up.config.driver = _tx.drv
	return up
}

// String implements the fmt.Stringer.
func (up *UserPlatform) String() string {
	var builder strings.Builder
	builder.WriteString("UserPlatform(")
	builder.WriteString(fmt.Sprintf("id=%v, ", up.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", up.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", up.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", up.UserID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(up.Platform)
	builder.WriteString(", ")
	builder.WriteString("platform_id=")
	builder.WriteString(up.PlatformID)
	builder.WriteString(", ")
	builder.WriteString("second_id=")
	builder.WriteString(up.SecondID)
	builder.WriteByte(')')
	return builder.String()
}

// UserPlatforms is a parsable slice of UserPlatform.
type UserPlatforms []*UserPlatform
