package storage

import (
	"context"
	"io"
	"net/url"
	"time"
)

// URLHandler provides URL generation and key extraction capabilities for storage backends.
// This interface enables URL-based access to stored files and reverse key lookup from URLs.
type URLHandler interface {
	// GenerateURL creates a public URL for accessing the file identified by the given key.
	// Optional params are intended for query-string options; when multiple values are
	// provided, only the first non-nil params is meaningful. An implementation may
	// ignore params: the urlhandler.Handler used by every driver in this module does.
	GenerateURL(key string, params ...url.Values) string

	// GenerateURLs creates public URLs for multiple files in batch, one per key
	// and in the same order. params are treated as in GenerateURL.
	GenerateURLs(keys []string, params ...url.Values) []string

	// ExtractKeyFromURL extracts the storage key from a public URL (or returns a
	// bare key unchanged). It returns "" when the key cannot be extracted.
	ExtractKeyFromURL(uri string) string

	// ExtractKeyFromURLWithMode extracts the storage key from a URL. When strict
	// is true, a URL whose host or base path does not match the public base is
	// rejected with an error instead of being parsed leniently.
	ExtractKeyFromURLWithMode(uri string, strict bool) (string, error)
}

// UploadAuthorizationType indicates how upload authorization should be interpreted by clients.
type UploadAuthorizationType string

const (
	// UploadAuthorizationTypeURL means UploadAuthorization.Value is a URL the
	// client sends the file body to with UploadAuthorization.Method
	// (s3 presigned PUT, fileserver one-time PUT).
	UploadAuthorizationTypeURL UploadAuthorizationType = "url"
	// UploadAuthorizationTypeToken means UploadAuthorization.Value is an upload
	// token for the provider's own upload API (qiniu form upload).
	UploadAuthorizationTypeToken UploadAuthorizationType = "token"
)

// UploadAuthorization carries the upload authorization data for client-side uploads.
type UploadAuthorization struct {
	// Type selects how Value is interpreted.
	Type UploadAuthorizationType `json:"type" yaml:"type"`
	// Value is the upload URL or token, depending on Type.
	Value string `json:"value" yaml:"value"`
	// Method is the HTTP method the client should use (PUT or POST).
	Method string `json:"method" yaml:"method"`
	// Headers is a reserved field for extra headers a client must send with the
	// upload request. No driver populates it today; it is kept intentionally as a
	// stable extension point, so do not remove it as "dead code".
	Headers map[string]string `json:"headers,omitempty" yaml:"headers,omitempty"`
}

// UploadFileInfo contains the finalized storage information for an upload.
type UploadFileInfo struct {
	// Key is the normalized storage key the upload will be stored under.
	Key string `json:"key" yaml:"key"`
	// URL is the public URL for Key, as produced by URLHandler.GenerateURL.
	URL string `json:"url" yaml:"url"`
}

// UploadAuthResult is the structured result for generating upload authorization.
type UploadAuthResult struct {
	Authorization UploadAuthorization `json:"authorization" yaml:"authorization"`
	File          UploadFileInfo      `json:"file" yaml:"file"`
}

// UploadNamingStrategy controls how upload file names are generated by
// BuildUploadFileName. The empty value means UploadNamingStrategyRandomExt.
type UploadNamingStrategy string

const (
	// UploadNamingStrategyRandomExt names the file with a random UUID plus the
	// original extension. It is the default.
	UploadNamingStrategyRandomExt UploadNamingStrategy = "random_ext"
	// UploadNamingStrategyHashExt names the file with the hex MD5 of the
	// original name plus its extension, so the same name always maps to the
	// same key.
	UploadNamingStrategyHashExt UploadNamingStrategy = "hash_ext"
	// UploadNamingStrategyOriginal keeps the base name of the original file.
	UploadNamingStrategyOriginal UploadNamingStrategy = "original"
)

// UploadAuthRequest describes the input for upload authorization generation.
type UploadAuthRequest struct {
	// FileName is the client's original file name; it is required and feeds
	// the driver's UploadNamingStrategy.
	FileName string `json:"file_name" yaml:"file_name"`
	// Dir is an optional relative business directory placed under the
	// driver's configured prefix directory (see JoinUploadKey).
	Dir string `json:"dir,omitempty" yaml:"dir,omitempty"`
	// TTL optionally shortens how long the generated authorization stays valid.
	// A zero value uses the driver's configured default TTL, which also caps this
	// field: a longer TTL is clamped down rather than honored, so populating it
	// from client input cannot extend a credential's lifetime.
	TTL time.Duration `json:"ttl,omitempty" yaml:"ttl,omitempty"`
}

// UploadAuthorizer provides secure upload authorization generation for client-side uploads.
// This is commonly used for direct-to-storage uploads from web browsers or mobile apps.
type UploadAuthorizer interface {
	// GenerateUploadAuth creates upload authorization and target file information.
	// The returned File.Key is final: the client uploads to it and the caller
	// should persist it. An empty or invalid req.FileName, or a req.Dir that is
	// absolute or escapes upward, is an error.
	GenerateUploadAuth(ctx context.Context, req UploadAuthRequest) (UploadAuthResult, error)
}

// FileUploader provides file upload capabilities to the storage backend.
type FileUploader interface {
	// UploadFile uploads data from a reader under key, replacing any existing
	// object. The returned key is NormalizeKey(key) and may differ from the
	// argument; persist that value. An invalid key fails with
	// storageerr.ErrFileNameInvalid.
	UploadFile(ctx context.Context, file io.Reader, key string) (string, error)

	// UploadLocalFile uploads the local file at path file under key, with the
	// same key rules as UploadFile. The source file is read, not moved.
	// Returns the normalized storage key or an error if upload fails.
	UploadLocalFile(ctx context.Context, file string, key string) (string, error)
}

// DownloadResult is the structured output for download operations.
type DownloadResult struct {
	// Reader streams the object body. The caller must close it.
	Reader io.ReadCloser
	// MIME is the content type; it may be empty when the driver cannot
	// determine one (drivers that derive it from the key's extension return
	// "" for unknown extensions).
	MIME string
	// Size is the object size in bytes.
	Size int64
}

// FileDownloader provides file download and existence checking capabilities.
type FileDownloader interface {
	// IsFileExists checks whether a file exists in the storage backend.
	// A missing key reports (false, nil); an error means the check itself failed.
	IsFileExists(ctx context.Context, key string) (bool, error)

	// DownloadFile retrieves a file from storage. A missing key fails with
	// storageerr.ErrNotFound. On success the caller is responsible for closing
	// DownloadResult.Reader.
	DownloadFile(ctx context.Context, key string) (DownloadResult, error)
}

// FileInfo carries lightweight object metadata returned by FileStater.
type FileInfo struct {
	// MIME is the content type of the object; it may be empty when the
	// backend does not record one.
	MIME string
	// Size is the object size in bytes.
	Size int64
}

// FileStater is an optional capability for cheaply retrieving object metadata
// (size and MIME type) without downloading the file body. Backends that expose
// a native stat/head operation implement it; callers should probe support with
// a type assertion since it is intentionally kept out of the core Storage
// interface.
type FileStater interface {
	// StatFile returns lightweight metadata for the file identified by key.
	// It returns storageerr.ErrNotFound when the key does not exist.
	StatFile(ctx context.Context, key string) (FileInfo, error)
}

// FileLister is an optional capability for enumerating stored keys under a
// prefix using cursor-based pagination. Callers should probe support with a
// type assertion; it is intentionally kept out of the core Storage interface.
type FileLister interface {
	// ListFiles returns up to limit keys under prefix, resuming after cursor
	// (pass an empty cursor for the first page). The returned next cursor is
	// non-empty when more keys may remain; feed it back on the following call.
	// An empty next cursor signals the end of the listing.
	//
	// Iterate until the next cursor is empty, not until a page comes back empty:
	// a backend may return a page with no keys while more remain. Treat the
	// cursor as opaque; some drivers return the last key of the page but others
	// return a backend-specific marker, so never construct one. limit is an
	// upper bound a driver may lower to its own maximum (Qiniu caps at 1000),
	// so a short page does not mean the listing is finished either.
	ListFiles(ctx context.Context, prefix, cursor string, limit int) (keys []string, next string, err error)
}

// FileDeleter provides file deletion capabilities.
type FileDeleter interface {
	// DeleteFile removes a file from the storage backend. Deletion is idempotent:
	// deleting a key that does not exist reports success rather than
	// storageerr.ErrNotFound.
	DeleteFile(ctx context.Context, key string) error
}

// FileMoverCopier provides file moving and copying operations within the storage backend.
type FileMoverCopier interface {
	// MoveFile relocates a file from source to destination key.
	// A missing source fails with storageerr.ErrNotFound. If overwrite is false
	// and the destination exists, it fails with storageerr.ErrDestExists; the
	// check is best-effort against concurrent writers on most drivers. Moving a
	// key onto itself is a no-op when the source exists.
	MoveFile(ctx context.Context, sourceKey string, destinationKey string, overwrite bool) error

	// CopyFile duplicates a file from source to destination key.
	// A missing source fails with storageerr.ErrNotFound. If overwrite is false
	// and the destination exists, it fails with storageerr.ErrDestExists.
	CopyFile(ctx context.Context, sourceKey string, destinationKey string, overwrite bool) error
}

// Storage combines the core file storage operations in a single interface.
// This is the primary interface for most file storage use cases.
type Storage interface {
	FileDeleter
	FileUploader
	FileDownloader
	FileMoverCopier
}

// CDNStorage extends Storage with token generation for secure uploads.
// This interface is suitable for cloud storage backends that support direct client uploads.
type CDNStorage interface {
	Storage
	URLHandler
	UploadAuthorizer
}
