package idgenerator

import (
	"fmt"
	"math"
	"sync"
	"testing"
)

func TestNextId(t *testing.T) {
	t.Log(NextId())
	t.Log(math.MaxInt32)
	t.Log(math.MaxInt64)
}

// TestParseWorkerID pins two rules that a fixed-value fallback silently broke.
//
// Zero must be accepted: the underlying generator's range is [0, 63], and
// deriving WORKER_ID from a StatefulSet pod ordinal makes "0" the single most
// common value in practice. Treating it as invalid mapped pod-0 onto the same
// worker ID as pod-1 and produced colliding IDs.
//
// A malformed value must fail rather than fall back, for the same reason: any
// fixed substitute is shared with whichever replica legitimately holds it.
func TestParseWorkerID(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		raw     string
		want    uint16
		wantErr bool
	}{
		{name: "unset uses the single-instance default", raw: "", want: defaultWorkerID},
		{name: "zero is a valid worker id", raw: "0", want: 0},
		{name: "ordinary value is used", raw: "42", want: 42},
		{name: "max worker id is valid", raw: "63", want: 63},
		{name: "above max is rejected", raw: "64", wantErr: true},
		{name: "above uint16 is rejected", raw: "65536", wantErr: true},
		{name: "non numeric is rejected", raw: "abc", wantErr: true},
		{name: "negative is rejected", raw: "-1", wantErr: true},
		{name: "trailing space is rejected", raw: "1 ", wantErr: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got, err := parseWorkerID(tt.raw)
			if tt.wantErr {
				if err == nil {
					t.Fatalf("parseWorkerID(%q) = (%d, nil), want an error", tt.raw, got)
				}
				return
			}
			if err != nil {
				t.Fatalf("parseWorkerID(%q) returned unexpected error: %v", tt.raw, err)
			}
			if got != tt.want {
				t.Errorf("parseWorkerID(%q) = %d, want %d", tt.raw, got, tt.want)
			}
		})
	}
}

// TestDistinctWorkerIDsProduceDistinctIDs is the property the worker ID exists
// to guarantee: two replicas configured with different worker IDs must never
// emit the same ID. Worker IDs 0 and 1 are the pod-0/pod-1 pair that used to
// collapse onto a single generator.
func TestDistinctWorkerIDsProduceDistinctIDs(t *testing.T) {
	const perWorker = 2000

	seen := make(map[int64]uint16, perWorker*2)
	for _, workerID := range []uint16{0, 1} {
		next := NewIdGenerator(workerID)
		for range perWorker {
			id := next()
			if other, dup := seen[id]; dup {
				t.Fatalf("worker %d and worker %d both produced id %d", other, workerID, id)
			}
			seen[id] = workerID
		}
	}
}

// TestAdversarialConcurrentIdGeneration runs 128 goroutines generating 128 IDs each,
// asserting strictly positive, strictly unique across the entire run.
func TestAdversarialConcurrentIdGeneration(t *testing.T) {
	const (
		numGoroutines   = 128
		idsPerGoroutine = 128
		totalExpected   = numGoroutines * idsPerGoroutine
	)

	var wg sync.WaitGroup
	idSlices := make([][]int64, numGoroutines)

	for g := range numGoroutines {
		wg.Add(1)
		go func(gID int) {
			defer wg.Done()
			ids := make([]int64, idsPerGoroutine)
			var prev int64
			for i := range idsPerGoroutine {
				id := NextId()
				if id <= 0 {
					t.Errorf("goroutine %d generated non-positive ID: %d", gID, id)
				}
				if id <= prev {
					t.Errorf("goroutine %d generated non-increasing ID: prev=%d, curr=%d", gID, prev, id)
				}
				prev = id
				ids[i] = id
			}
			idSlices[gID] = ids
		}(g)
	}

	wg.Wait()

	// Global uniqueness check
	seen := make(map[int64]int, totalExpected)
	for gID, ids := range idSlices {
		for idx, id := range ids {
			if prevG, found := seen[id]; found {
				t.Fatalf("COLLISION DETECTED: ID %d generated by g%d (idx %d) and g%d", id, gID, idx, prevG)
			}
			seen[id] = gID
		}
	}

	if len(seen) != totalExpected {
		t.Fatalf("Total unique IDs = %d, expected %d", len(seen), totalExpected)
	}

	t.Logf("Adversarial IdGenerator test passed: %d unique IDs across %d goroutines", totalExpected, numGoroutines)
}

// TestAdversarialMultiWorkerIndependence tests all valid worker IDs (0..63) concurrently.
func TestAdversarialMultiWorkerIndependence(t *testing.T) {
	const (
		maxWorkers      = 64
		idsPerGenerator = 2000
	)

	var wg sync.WaitGroup
	allGenerated := sync.Map{}

	for w := range uint16(maxWorkers) {
		wg.Add(1)
		go func(workerID uint16) {
			defer wg.Done()
			gen := NewIdGenerator(workerID)
			var prev int64
			for range idsPerGenerator {
				id := gen()
				if id <= 0 {
					t.Errorf("worker %d generated non-positive ID: %d", workerID, id)
				}
				if id <= prev {
					t.Errorf("worker %d non-monotonic ID: prev=%d, curr=%d", workerID, prev, id)
				}
				prev = id

				if actualWorker, exists := allGenerated.LoadOrStore(id, workerID); exists {
					t.Errorf("COLLISION across workers: ID %d generated by worker %d and worker %v", id, workerID, actualWorker)
				}
			}
		}(w)
	}

	wg.Wait()
}

// TestAdversarialParseWorkerIDExhaustive tests exhaustive boundary conditions.
func TestAdversarialParseWorkerIDExhaustive(t *testing.T) {
	cases := []struct {
		input   string
		want    uint16
		wantErr bool
	}{
		// Valid cases
		{"", 1, false},
		{"0", 0, false},
		{"1", 1, false},
		{"62", 62, false},
		{"63", 63, false},

		// Invalid cases (boundaries & invalid formats)
		{"64", 0, true},
		{"65", 0, true},
		{"100", 0, true},
		{"65535", 0, true},
		{"65536", 0, true},
		{"-0", 0, true},
		{"-1", 0, true},
		{"-63", 0, true},
		{fmt.Sprintf("%d", math.MaxInt64), 0, true},
		{" 1", 0, true},
		{"1 ", 0, true},
		{"1\n", 0, true},
		{"1.0", 0, true},
		{"0x10", 0, true},
		{"one", 0, true},
		{"null", 0, true},
		{"undefined", 0, true},
		{"①", 0, true},
	}

	for _, tc := range cases {
		t.Run(fmt.Sprintf("case_%q", tc.input), func(t *testing.T) {
			got, err := parseWorkerID(tc.input)
			if (err != nil) != tc.wantErr {
				t.Fatalf("parseWorkerID(%q) error = %v, wantErr = %v", tc.input, err, tc.wantErr)
			}
			if !tc.wantErr && got != tc.want {
				t.Fatalf("parseWorkerID(%q) = %d, want %d", tc.input, got, tc.want)
			}
		})
	}
}

// TestStressConcurrentIdGeneration satisfies Objective 3:
// 50+ concurrent goroutines generating IDs, verifying strictly unique, increasing integers.
func TestStressConcurrentIdGeneration(t *testing.T) {
	const (
		numGoroutines   = 64
		idsPerGoroutine = 5000
		totalExpected   = numGoroutines * idsPerGoroutine
	)

	var wg sync.WaitGroup
	idMatrix := make([][]int64, numGoroutines)

	for g := range numGoroutines {
		wg.Add(1)
		go func(gID int) {
			defer wg.Done()
			ids := make([]int64, idsPerGoroutine)
			for i := range idsPerGoroutine {
				id := NextId()
				if id <= 0 {
					t.Errorf("goroutine %d generated non-positive ID: %d", gID, id)
				}
				if i > 0 && id <= ids[i-1] {
					t.Errorf("goroutine %d generated non-increasing ID: prev=%d, curr=%d", gID, ids[i-1], id)
				}
				ids[i] = id
			}
			idMatrix[gID] = ids
		}(g)
	}

	wg.Wait()

	// Verify all generated IDs across all goroutines are strictly unique
	seen := make(map[int64]int, totalExpected)
	for gID, ids := range idMatrix {
		for idx, id := range ids {
			if prevG, exists := seen[id]; exists {
				t.Fatalf("Duplicate ID %d detected! Generated by goroutine %d (index %d) and goroutine %d",
					id, gID, idx, prevG)
			}
			seen[id] = gID
		}
	}

	if len(seen) != totalExpected {
		t.Fatalf("Total unique IDs = %d, want %d", len(seen), totalExpected)
	}

	t.Logf("Successfully generated and verified %d strictly unique IDs across %d concurrent goroutines",
		totalExpected, numGoroutines)
}

// TestStressIndependentWorkerGenerators verifies independent instances of NewIdGenerator
// running across different worker IDs concurrently.
func TestStressIndependentWorkerGenerators(t *testing.T) {
	workerIDs := []uint16{0, 1, 10, 31, 63}
	const count = 1000

	var wg sync.WaitGroup
	allIDs := sync.Map{}

	for _, wID := range workerIDs {
		wg.Add(1)
		go func(w uint16) {
			defer wg.Done()
			gen := NewIdGenerator(w)
			var prev int64
			for i := range count {
				id := gen()
				if id <= 0 {
					t.Errorf("worker %d generated non-positive ID: %d", w, id)
				}
				if i > 0 && id <= prev {
					t.Errorf("worker %d non-increasing ID: prev=%d, curr=%d", w, prev, id)
				}
				prev = id

				if _, loaded := allIDs.LoadOrStore(id, w); loaded {
					t.Errorf("collision detected on ID %d from worker %d", id, w)
				}
			}
		}(wID)
	}

	wg.Wait()
}

// TestWorkerIDParsingBoundary tests parseWorkerID edge cases.
func TestWorkerIDParsingBoundary(t *testing.T) {
	cases := []struct {
		input   string
		want    uint16
		wantErr bool
	}{
		{"", 1, false},
		{"0", 0, false},
		{"1", 1, false},
		{"63", 63, false},
		{"64", 0, true},
		{"-1", 0, true},
		{"abc", 0, true},
		{"99999", 0, true},
	}

	for _, tc := range cases {
		t.Run(fmt.Sprintf("input_%s", tc.input), func(t *testing.T) {
			got, err := parseWorkerID(tc.input)
			if (err != nil) != tc.wantErr {
				t.Fatalf("parseWorkerID(%q) error = %v, wantErr = %v", tc.input, err, tc.wantErr)
			}
			if !tc.wantErr && got != tc.want {
				t.Fatalf("parseWorkerID(%q) = %d, want %d", tc.input, got, tc.want)
			}
		})
	}
}
