package idgenerator

import (
	"errors"
	"os"
	"os/exec"
	"sync"
	"testing"
	"time"
)

// TestBaseTimeIsAbsolute pins the epoch to a zone-independent instant, and to
// the property that makes changing it safe.
//
// BaseTime used to be time.Date(2024, 1, 1, 0, 0, 0, 0, time.Local), so the tick
// a process counted from depended on the zone time.Local held when the epoch was
// evaluated (boot used to assign it from its package init; main may still call
// boot.InitTimezone) and on whether the image ships tzdata:
// the same instant became ticks hours apart, and a restart under a different
// zone re-issued tick ranges the same worker ID had already used. Re-deriving
// the value from a zone would therefore fail here on any machine not running in
// UTC+14, which is the point.
//
// The loop covers the other direction: a base later than an actual zone's
// 2024-01-01 would make ticks go backwards relative to IDs already issued under
// the old expression and could repeat them, so no zone may reach the date
// before baseTimeMillis does.
func TestBaseTimeIsAbsolute(t *testing.T) {
	t.Parallel()

	earliest := time.Date(2024, 1, 1, 0, 0, 0, 0, time.FixedZone("UTC+14", 14*60*60)).UnixMilli()
	if baseTimeMillis != earliest {
		t.Errorf("baseTimeMillis = %d, want the earliest 2024-01-01 (UTC+14) = %d", baseTimeMillis, earliest)
	}

	for _, offset := range []int{-12, -8, -5, 0, 5, 8, 9, 14} {
		zone := time.FixedZone("test", offset*60*60)
		if local := time.Date(2024, 1, 1, 0, 0, 0, 0, zone).UnixMilli(); local < baseTimeMillis {
			t.Errorf("UTC%+d reaches 2024-01-01 at %d, before baseTimeMillis %d: ticks would retrace IDs issued under a zone-dependent base", offset, local, baseTimeMillis)
		}
	}
}

// TestParseWorkerID pins two rules that a fixed-value fallback silently broke.
//
// Zero must be accepted: the underlying generator's range is [0, 63], and
// deriving WORKER_ID from a StatefulSet pod ordinal makes "0" the single most
// common value in practice. Treating it as invalid mapped pod-0 onto the same
// worker ID as pod-1 and produced colliding IDs.
//
// A malformed value must fail rather than fall back, for the same reason: any
// fixed substitute is shared with whichever replica legitimately holds it.
func TestParseWorkerID(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		raw     string
		want    uint16
		wantErr bool
	}{
		{name: "unset uses the single-instance default", raw: "", want: defaultWorkerID},
		{name: "zero is a valid worker id", raw: "0", want: 0},
		{name: "ordinary value is used", raw: "42", want: 42},
		{name: "max worker id is valid", raw: "63", want: 63},
		{name: "above max is rejected", raw: "64", wantErr: true},
		{name: "above uint16 is rejected", raw: "65536", wantErr: true},
		{name: "non numeric is rejected", raw: "abc", wantErr: true},
		{name: "negative is rejected", raw: "-1", wantErr: true},
		{name: "trailing space is rejected", raw: "1 ", wantErr: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got, err := parseWorkerID(tt.raw)
			if tt.wantErr {
				if err == nil {
					t.Fatalf("parseWorkerID(%q) = (%d, nil), want an error", tt.raw, got)
				}
				return
			}
			if err != nil {
				t.Fatalf("parseWorkerID(%q) returned unexpected error: %v", tt.raw, err)
			}
			if got != tt.want {
				t.Errorf("parseWorkerID(%q) = %d, want %d", tt.raw, got, tt.want)
			}
		})
	}
}

// TestDistinctWorkerIDsProduceDistinctIDs is the property the worker ID exists
// to guarantee: two replicas configured with different worker IDs must never
// emit the same ID. Worker IDs 0 and 1 are the pod-0/pod-1 pair that used to
// collapse onto a single generator.
func TestDistinctWorkerIDsProduceDistinctIDs(t *testing.T) {
	const perWorker = 2000

	seen := make(map[int64]uint16, perWorker*2)
	for _, workerID := range []uint16{0, 1} {
		next := NewIdGenerator(workerID)
		for range perWorker {
			id := next()
			if other, dup := seen[id]; dup {
				t.Fatalf("worker %d and worker %d both produced id %d", other, workerID, id)
			}
			seen[id] = workerID
		}
	}
}

func TestConcurrentIDGeneration(t *testing.T) {
	const (
		numGoroutines   = 16
		idsPerGoroutine = 64
		totalExpected   = numGoroutines * idsPerGoroutine
	)

	var wg sync.WaitGroup
	idSlices := make([][]int64, numGoroutines)

	for g := range numGoroutines {
		wg.Go(func() {
			ids := make([]int64, idsPerGoroutine)
			var prev int64
			for i := range idsPerGoroutine {
				id := NextId()
				if id <= 0 {
					t.Errorf("goroutine %d generated non-positive ID: %d", g, id)
				}
				if id <= prev {
					t.Errorf("goroutine %d generated non-increasing ID: prev=%d, curr=%d", g, prev, id)
				}
				prev = id
				ids[i] = id
			}
			idSlices[g] = ids
		})
	}

	wg.Wait()

	seen := make(map[int64]int, totalExpected)
	for gID, ids := range idSlices {
		for idx, id := range ids {
			if prevG, found := seen[id]; found {
				t.Fatalf("COLLISION DETECTED: ID %d generated by g%d (idx %d) and g%d", id, gID, idx, prevG)
			}
			seen[id] = gID
		}
	}

	if len(seen) != totalExpected {
		t.Fatalf("Total unique IDs = %d, expected %d", len(seen), totalExpected)
	}
}

// resetGlobal forgets the process-global generator so a test can exercise its
// one-time initialization. Tests that call it must not run in parallel.
func resetGlobal(t *testing.T) {
	t.Helper()
	reset := func() {
		globalOnce = sync.Once{}
		global = nil
		globalErr = nil
	}
	reset()
	t.Cleanup(reset)
}

// workerOf extracts the worker ID from an ID built with the default layout
// (6 worker bits above 6 sequence bits).
func workerOf(id int64) int64 {
	return (id >> 6) & 63
}

func mustPanic(t *testing.T, name string, f func()) {
	t.Helper()
	defer func() {
		if recover() == nil {
			t.Fatalf("%s did not panic", name)
		}
	}()
	f()
}

// TestImportHasNoSideEffects pins that a malformed WORKER_ID no longer takes
// down every binary that merely links the package: the package init used to
// parse it and panic. Checked in a child process, because this one's init has
// already run.
func TestImportHasNoSideEffects(t *testing.T) {
	if os.Getenv("IDGEN_IMPORT_CHILD") == "1" {
		os.Exit(0)
	}
	cmd := exec.Command(os.Args[0], "-test.run=^TestImportHasNoSideEffects$")
	cmd.Env = append(os.Environ(), "IDGEN_IMPORT_CHILD=1", "WORKER_ID=not-a-number")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("process with a malformed WORKER_ID failed before using the package: %v\n%s", err, out)
	}
}

func TestNextIdLazilyInitializesFromEnv(t *testing.T) {
	t.Run("WORKER_ID is used", func(t *testing.T) {
		resetGlobal(t)
		t.Setenv("WORKER_ID", "5")
		if got := workerOf(NextId()); got != 5 {
			t.Fatalf("worker of NextId() = %d, want 5", got)
		}
	})
	t.Run("unset WORKER_ID defaults to 1", func(t *testing.T) {
		resetGlobal(t)
		t.Setenv("WORKER_ID", "")
		if got := workerOf(NextId()); got != int64(defaultWorkerID) {
			t.Fatalf("worker of NextId() = %d, want %d", got, defaultWorkerID)
		}
	})
	t.Run("explicit init after lazy init is rejected", func(t *testing.T) {
		resetGlobal(t)
		t.Setenv("WORKER_ID", "5")
		NextId()
		if err := Init(7); !errors.Is(err, ErrAlreadyInitialized) {
			t.Fatalf("Init after NextId = %v, want ErrAlreadyInitialized", err)
		}
		if err := InitFromEnv(); !errors.Is(err, ErrAlreadyInitialized) {
			t.Fatalf("InitFromEnv after NextId = %v, want ErrAlreadyInitialized", err)
		}
		if got := workerOf(NextId()); got != 5 {
			t.Fatalf("worker after rejected Init = %d, want 5", got)
		}
	})
}

func TestInit(t *testing.T) {
	t.Run("explicit worker ID wins over WORKER_ID", func(t *testing.T) {
		resetGlobal(t)
		t.Setenv("WORKER_ID", "9")
		if err := Init(0); err != nil {
			t.Fatalf("Init(0) = %v", err)
		}
		if got := workerOf(NextId()); got != 0 {
			t.Fatalf("worker of NextId() = %d, want 0", got)
		}
		if err := Init(3); !errors.Is(err, ErrAlreadyInitialized) {
			t.Fatalf("second Init = %v, want ErrAlreadyInitialized", err)
		}
	})
	t.Run("out of range worker ID is rejected without consuming the init", func(t *testing.T) {
		resetGlobal(t)
		if err := Init(64); err == nil || errors.Is(err, ErrAlreadyInitialized) {
			t.Fatalf("Init(64) = %v, want a range error", err)
		}
		if err := Init(63); err != nil {
			t.Fatalf("Init(63) after a rejected Init = %v", err)
		}
		if got := workerOf(NextId()); got != 63 {
			t.Fatalf("worker of NextId() = %d, want 63", got)
		}
	})
	t.Run("InitFromEnv reads WORKER_ID", func(t *testing.T) {
		resetGlobal(t)
		t.Setenv("WORKER_ID", "12")
		if err := InitFromEnv(); err != nil {
			t.Fatalf("InitFromEnv() = %v", err)
		}
		if got := workerOf(NextId()); got != 12 {
			t.Fatalf("worker of NextId() = %d, want 12", got)
		}
	})
}

// TestInvalidWorkerID pins where a malformed WORKER_ID fails now that package
// init no longer panics: InitFromEnv returns the error, and NextId panics on
// every call rather than once — a recovered first panic must not leave a
// generator running on some fallback worker ID.
func TestInvalidWorkerID(t *testing.T) {
	t.Run("InitFromEnv returns the error", func(t *testing.T) {
		resetGlobal(t)
		t.Setenv("WORKER_ID", "abc")
		if err := InitFromEnv(); err == nil {
			t.Fatal("InitFromEnv() with WORKER_ID=abc returned nil")
		}
		mustPanic(t, "NextId after failed InitFromEnv", func() { NextId() })
	})
	t.Run("lazy NextId panics on every call", func(t *testing.T) {
		resetGlobal(t)
		t.Setenv("WORKER_ID", "64")
		mustPanic(t, "first NextId", func() { NextId() })
		mustPanic(t, "second NextId", func() { NextId() })
		if err := Init(1); !errors.Is(err, ErrAlreadyInitialized) {
			t.Fatalf("Init after failed lazy init = %v, want ErrAlreadyInitialized", err)
		}
	})
}
