// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             (unknown)
// source: dash/v1/admin.proto

package dashv1

import (
	context "context"
	gin "github.com/gin-gonic/gin"
	ginx "github.com/tbxark/sphere/pkg/web/ginx"
)

var _ = new(context.Context)
var _ = new(gin.Context)
var _ = new(ginx.DataResponse[string])

type AdminServiceHTTPServer interface {
	AdminCreate(context.Context, *AdminCreateRequest) (*AdminCreateResponse, error)
	AdminDelete(context.Context, *AdminDeleteRequest) (*AdminDeleteResponse, error)
	AdminDetail(context.Context, *AdminDetailRequest) (*AdminDetailResponse, error)
	AdminList(context.Context, *AdminListRequest) (*AdminListResponse, error)
	AdminUpdate(context.Context, *AdminUpdateRequest) (*AdminUpdateResponse, error)
}

// @Summary AdminList
// @Description AdminList
// @Tags dash.v1
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Success 200 {object} ginx.DataResponse[AdminListResponse]
// @Router /api/admin/list [get]
func _AdminService_AdminList0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx *gin.Context) {
	return ginx.WithJson(func(ctx *gin.Context) (*AdminListResponse, error) {
		var in AdminListRequest
		out, err := srv.AdminList(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary AdminCreate
// @Description AdminCreate
// @Tags dash.v1
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param request body AdminCreateRequest true "Request body"
// @Success 200 {object} ginx.DataResponse[AdminCreateResponse]
// @Router /api/admin/create [post]
func _AdminService_AdminCreate0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx *gin.Context) {
	return ginx.WithJson(func(ctx *gin.Context) (*AdminCreateResponse, error) {
		var in AdminCreateRequest
		if err := ginx.ShouldBindJSON(ctx, &in); err != nil {
			return nil, err
		}
		out, err := srv.AdminCreate(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary AdminUpdate
// @Description AdminUpdate
// @Tags dash.v1
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param id path integer true "id"
// @Param request body AdminUpdateRequest true "Request body"
// @Success 200 {object} ginx.DataResponse[AdminUpdateResponse]
// @Router /api/admin/update/{id} [post]
func _AdminService_AdminUpdate0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx *gin.Context) {
	return ginx.WithJson(func(ctx *gin.Context) (*AdminUpdateResponse, error) {
		var in AdminUpdateRequest
		if err := ginx.ShouldBindJSON(ctx, &in); err != nil {
			return nil, err
		}
		if err := ginx.ShouldBindUri(ctx, &in); err != nil {
			return nil, err
		}
		out, err := srv.AdminUpdate(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary AdminDetail
// @Description AdminDetail
// @Tags dash.v1
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param id path integer true "id"
// @Success 200 {object} ginx.DataResponse[AdminDetailResponse]
// @Router /api/admin/detail/{id} [get]
func _AdminService_AdminDetail0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx *gin.Context) {
	return ginx.WithJson(func(ctx *gin.Context) (*AdminDetailResponse, error) {
		var in AdminDetailRequest
		if err := ginx.ShouldBindUri(ctx, &in); err != nil {
			return nil, err
		}
		out, err := srv.AdminDetail(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary AdminDelete
// @Description AdminDelete
// @Tags dash.v1
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param id path integer true "id"
// @Success 200 {object} ginx.DataResponse[AdminDeleteResponse]
// @Router /api/admin/delete/{id} [delete]
func _AdminService_AdminDelete0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx *gin.Context) {
	return ginx.WithJson(func(ctx *gin.Context) (*AdminDeleteResponse, error) {
		var in AdminDeleteRequest
		if err := ginx.ShouldBindUri(ctx, &in); err != nil {
			return nil, err
		}
		out, err := srv.AdminDelete(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterAdminServiceHTTPServer(route gin.IRouter, srv AdminServiceHTTPServer) {
	r := route.Group("/")
	r.GET("/api/admin/list", _AdminService_AdminList0_HTTP_Handler(srv))
	r.POST("/api/admin/create", _AdminService_AdminCreate0_HTTP_Handler(srv))
	r.POST("/api/admin/update/:id", _AdminService_AdminUpdate0_HTTP_Handler(srv))
	r.GET("/api/admin/detail/:id", _AdminService_AdminDetail0_HTTP_Handler(srv))
	r.DELETE("/api/admin/delete/:id", _AdminService_AdminDelete0_HTTP_Handler(srv))
}
