// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             (unknown)
// source: dash/v1/system.proto

package dashv1

import (
	context "context"
	gin "github.com/gin-gonic/gin"
	ginx "github.com/tbxark/sphere/pkg/web/ginx"
)

var _ = new(context.Context)
var _ = new(gin.Context)
var _ = new(ginx.DataResponse[string])

type SystemServiceHTTPServer interface {
	CacheReset(context.Context, *CacheResetRequest) (*CacheResetResponse, error)
}

// @Summary CacheReset
// @Description CacheReset
// @Tags dash.v1
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param request body CacheResetRequest true "Request body"
// @Success 200 {object} ginx.DataResponse[CacheResetResponse]
// @Router /api/cache/reset [post]
func _SystemService_CacheReset0_HTTP_Handler(srv SystemServiceHTTPServer) func(ctx *gin.Context) {
	return ginx.WithJson(func(ctx *gin.Context) (*CacheResetResponse, error) {
		var in CacheResetRequest
		if err := ginx.ShouldBindJSON(ctx, &in); err != nil {
			return nil, err
		}
		out, err := srv.CacheReset(ctx, &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterSystemServiceHTTPServer(route gin.IRouter, srv SystemServiceHTTPServer) {
	r := route.Group("/")
	r.POST("/api/cache/reset", _SystemService_CacheReset0_HTTP_Handler(srv))
}
