// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// KeyValueStore is the predicate function for keyvaluestore builders.
type KeyValueStore func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPlatform is the predicate function for userplatform builders.
type UserPlatform func(*sql.Selector)
