FROM scratch
COPY --from=builder {{ binary_name }} /main

{% for key, value in envs %}
ENV {{ key }} {{ value }}
{% endfor %}

ENTRYPOINT ["/main"]

{% if cmd_args is defined %}
CMD {{ cmd_args }}
{% endif %}
