// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/tbxark/go-base-api/config"
	"github.com/tbxark/go-base-api/internal/biz/bot"
)

// Injectors from wire.go:

func NewApplication(cfg *config.Config) (*bot.App, error) {
	botConfig := cfg.Bot
	app := bot.NewApp(botConfig)
	return app, nil
}
